"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const main_1 = require("./main");
const owner1 = new main_1.Transport.OwnerClass("Капранов", "Василий", "Генадьевич", new Date(1990, 1, 1), main_1.Transport.TypeOfDocument.Passport, "1234", "567890");
const car1 = new main_1.Transport.CarImpl("Toyota", "Camry", 2020, "QWERTYU789632", "ABC123", owner1, main_1.Transport.BodyType.Sedan, main_1.Transport.CarClass.Luxury);
const motorbike1 = new main_1.Transport.MotorbikeImpl("Yamaha", "YZF-R1", 2021, "SRFGGDFGHYHB8889", "XYZ789", owner1, "Sport", true);
const storage = new main_1.Transport.VehicleStorageImpl();
storage.addVehicle(car1);
storage.addVehicle(motorbike1);
storage.getAllVehicles().forEach(vehicle => vehicle.printInfo());
